src/main/java/hello/roommate/home/controller/HomeController.java
src/main/java/hello/roommate/home/domain/Weather.java
src/main/java/hello/roommate/home/repository/WeatherRepository.java
src/main/java/hello/roommate/home/service/WeatherRequest.java
src/main/java/hello/roommate/home/service/WeatherService.java
src/main/resources/application.properties
src/main/resources/static/index.html
src/test/java/hello/roommate/home/repository/NoticeRepositoryTest.java
src/test/java/hello/roommate/home/repository/WeatherRepositoryTest.java
src/test/java/hello/roommate/home/service/WeatherService.java
src/test/resources/application.properties
src/test/resources/schema.sql

- 공공데이터의 날씨 정보 저장할 repository 구현
- 날씨 정보 저장할 save() 구현
- 예측 시간으로 날씨 정보를 찾는 findByFcstTime 구현
- 날씨 정보를 업데이트하는 update 구현

Feat: 날씨 repository 구현

---

src/main/java/hello/roommate/RoommateApplication.java
src/main/java/hello/roommate/home/domain/Weather.java
src/main/java/hello/roommate/home/repository/WeatherExtremesRepository.java
src/main/java/hello/roommate/home/repository/WeatherRepository.java
src/main/java/hello/roommate/member/Dormitory.java
src/main/java/hello/roommate/member/Member.java
src/main/java/hello/roommate/profile/domain/Profile.java
src/main/java/hello/roommate/recommendation/domain/LifeStyle.java
src/main/java/hello/roommate/recommendation/domain/Recommendation.java
src/test/resources/schema.sql

- LifeStyle : 사용자 생활 패턴 정보 도메인
- Profile : 사용자 프로필 정보 도메인
- Recommendation : 추천 결과 저장할 도메인
- Member : 회원 관련 정보

Feat: 추천 화면에 필요한 도메인 설정

---

src/main/java/hello/roommate/home/repository/WeatherRepository.java
src/main/java/hello/roommate/member/domain/Dormitory.java
src/main/java/hello/roommate/member/domain/Member.java
src/main/java/hello/roommate/member/repository/MemberRepository.java
src/main/java/hello/roommate/profile/domain/Profile.java
src/main/java/hello/roommate/profile/repository/ProfileRepository.java
src/main/java/hello/roommate/profile/repository/ProfileUpdateDto.java
src/main/java/hello/roommate/recommendation/repository/LifeStyleRepository.java
src/main/java/hello/roommate/recommendation/repository/LifeStyleUpdateDto.java
src/main/java/hello/roommate/recommendation/repository/RecommendationRepository.java
src/main/java/hello/roommate/recommendation/repository/RecommendationUpdateDto.java

- 각 repository의 save, findById, delete, update 구현

Feat : Member, LifeStyle, Recommendation, Profile repository 구현 

---

src/main/resources/static/index.html

static/index.html에서 test -> test123으로 test change

First Commit

---

src/main/java/hello/roommate/RoommateApplication.java
src/main/java/hello/roommate/init/OptionInit.java
src/main/java/hello/roommate/init/PreferenceInit.java
src/main/java/hello/roommate/init/TestDataInit.java
src/main/java/hello/roommate/recommendation/domain/Option.java
src/test/java/hello/roommate/member/repository/MemberRepositoryTest.java

- Preference 초기 테스트 데이터 생성하는 PreferenceInit 구현

Feat : Preference 초기 테스트 데이터 생성 하는 기능 구현

---

src/main/java/hello/roommate/RoommateApplication.java
src/main/java/hello/roommate/home/service/WeatherService.java
src/main/java/hello/roommate/init/LifeStyleInit.java
src/main/java/hello/roommate/init/PreferenceInit.java
src/main/java/hello/roommate/init/TestDataInit.java
src/main/java/hello/roommate/member/controller/MemberController.java
src/main/java/hello/roommate/member/repository/MemberRepository.java
src/main/java/hello/roommate/member/service/MemberService.java
src/main/java/hello/roommate/recommendation/domain/LifeStyle.java
src/main/java/hello/roommate/recommendation/domain/Preference.java
src/main/java/hello/roommate/recommendation/service/LifestyleService.java
src/main/java/hello/roommate/recommendation/service/PreferenceService.java
src/test/java/hello/roommate/member/service/MemberServiceTest.java
src/test/java/hello/roommate/recommendation/service/LifeStyleServiceTest.java

- 원하는 상대방에 맞는 사람 찾아서 추천해주는 추천 기능 구현
- 검색 조건을 이용해서 원하는 사람 찾는 검색 기능 구현

Feat : 추천, 검색 기능 구현

---

src/main/java/hello/roommate/member/controller/MemberController.java

Controller->RestController

---

src/main/java/hello/roommate/member/domain/Member.java
src/main/java/hello/roommate/recommendation/domain/Option.java
src/main/java/hello/roommate/recommendation/domain/enums/Eating.java

feat: Add Member Class에 Gender Enum 관련 수정.

feat: Add Gender Enum in domain package

---

build.gradle
src/main/java/hello/roommate/chat/repository/MessageRepository.java
src/main/java/hello/roommate/chat/service/MessageService.java
src/test/java/hello/roommate/chat/repository/MessageRepositoryTest.java

- 해당 채팅방의 Id를 입력 받아 그 채팅방의 가장 최근 메시지를 찾아서 반환

Feat : 가장 최근 메시지 찾는 메서드 구현

---

src/main/java/hello/roommate/chat/controller/ChatRoomController.java
src/main/java/hello/roommate/chat/controller/MessageController.java
src/main/java/hello/roommate/chat/controller/WebSocketController.java
src/main/java/hello/roommate/chat/domain/ChatRoom.java
src/main/java/hello/roommate/chat/dto/ChatRoomDTO.java
src/main/java/hello/roommate/chat/dto/MessageDTO.java
src/main/java/hello/roommate/chat/service/ChatRoomService.java
src/main/java/hello/roommate/chat/service/MessageService.java
src/main/java/hello/roommate/member/controller/MemberController.java
src/main/java/hello/roommate/member/service/MemberService.java

- 나의 모든 채팅방 목록 반환하는 컨트롤러 구현
- 메시지 저장 후 전송하는 컨트롤러 구현
- 해당 채팅방의 모든 메시지 내역 조회하는 컨트롤러 구현

feat: 채팅 컨트롤러 구현

---

src/main/java/hello/roommate/auth/controller/KakaoAuthControllerNew.java
src/test/java/hello/roommate/member/repository/MemberRepositoryTest.java

- 프론트에서 액세스토큰을 넘겨줘서 사용자 정보조회요청으로 간결하게 변경

feat : 인가코드 없애고 액세스토큰방식으로 변경

---

src/main/java/hello/roommate/auth/controller/SignUpController.java
src/main/java/hello/roommate/auth/dto/EditMemberDTO.java
src/main/java/hello/roommate/auth/dto/SignUpDTO.java
src/main/java/hello/roommate/auth/service/KakaoAuthService.java
src/main/java/hello/roommate/auth/service/SignUpService.java
src/main/java/hello/roommate/recommendation/dto/PreferenceDTO.java

feat : 사용자 정보 수정 DTO 생성
feat : registerMember()에 setIntroduce() 추가

feat : 사용자 정보 수정 method 추가 및 기타 등등

---

src/main/java/hello/roommate/auth/controller/SignUpController.java
src/main/java/hello/roommate/auth/dto/SignUpDTO.java
src/main/java/hello/roommate/auth/service/SignUpService.java
src/main/java/hello/roommate/recommendation/dto/LifeStyleDTO.java
src/main/java/hello/roommate/recommendation/dto/PreferenceDTO.java
src/main/java/hello/roommate/recommendation/service/LifestyleService.java
src/main/java/hello/roommate/recommendation/service/PreferenceService.java

feat : DTO의 Option 타입을 List<String, List<Long>> 수정.
feat : LifeStyle, Preference DTO option 타입 수정
feat: 위에서 타입수정에 따른 controller 함수부분도 수정

Lhy : DTP의 Option 타입 수정

---

src/main/java/hello/roommate/auth/controller/SignUpController.java
src/main/java/hello/roommate/auth/service/SignUpService.java
src/main/java/hello/roommate/member/controller/MemberController.java

및 SignupService의 memberService 오타수정

refactor : 기존에 SignUpController에 있던 edit() method 위치 MemberController로 이동

---

src/main/java/hello/roommate/auth/service/SignUpService.java

feat: EditLifeStyle, EditPreference에 기존 LifeStyle, Preference 객체 삭제 후 저장하도록 변경

feat: EditLifeStyle, EditPreference에 기존 LifeStyle, Preference 객체 삭제 후 저장하도록 변경

---

src/main/java/hello/roommate/auth/dto/EditMemberDTO.java
src/main/java/hello/roommate/auth/service/SignUpService.java
src/main/java/hello/roommate/member/controller/MemberController.java

feat: EditMemberDTO에 set.gender 가능하게 수정.

feat: EditMemberDTO에 set.gender 가능하게 수정.

---

src/main/java/hello/roommate/auth/dto/SignUpDTO.java
src/main/java/hello/roommate/auth/service/SignUpService.java
src/main/java/hello/roommate/init/PreferenceInit.java
src/main/java/hello/roommate/member/controller/MemberController.java
src/main/java/hello/roommate/member/service/MemberService.java
src/main/java/hello/roommate/recommendation/domain/Option.java
src/main/java/hello/roommate/recommendation/dto/LifeStyleDTO.java
src/main/java/hello/roommate/recommendation/dto/PreferenceDTO.java

feat : 사용자의 회원번호를 통해 사용자의 Basic_Profile, LifeStyle, Preference 반환

feat : 상대 회원번호를 통해 상대 Basic_Profile, LifeStyle, Preference 반환

---

src/main/java/hello/roommate/member/controller/MemberController.java
src/main/java/hello/roommate/member/service/MemberService.java

deleteMemberCascade()로 선행되는 LifeStyle, Preference부터 삭제 후 Member삭제 실행

feat : 회원 탈퇴 기능 구현

---

src/main/java/hello/roommate/member/domain/Member.java
src/test/java/hello/roommate/member/repository/MemberRepositoryTest.java
src/test/java/hello/roommate/recommendation/service/LifeStyleServiceTest.java
src/test/resources/application-dev.properties
src/test/resources/application.properties

- 로컬 환경에서의 테스트, 개발 환경 테스트 설정 파일 추가
- 테스트 버그 수정

feat: test 코드 설정 파일 변경

---

src/main/resources/application-dev.properties

- spring.datasource.url 설정의 앞 공백 삭제

fix: application-dev.properties 오류 수정

---

src/main/java/hello/roommate/member/controller/MemberController.java
src/main/java/hello/roommate/member/repository/MemberCustomRepository.java
src/main/java/hello/roommate/member/service/MemberService.java
src/main/java/hello/roommate/recommendation/controller/RecommendController.java
src/main/java/hello/roommate/recommendation/service/RecommendService.java
src/test/java/hello/roommate/recommendation/service/RecommendServiceTest.java

fix: 추천 알고리즘 수정
refactor: 추천 목록 관련 API를 RecommendController로 이동
- 기존 알고리즘: 나와 동일한 기숙사 사람과 유사도 계산
- 변경 알고리즘: 모든 멤버와 유사도 계산

fix: 추천 알고리즘 수정

---

src/main/java/hello/roommate/init/LifeStyleInit.java
src/main/java/hello/roommate/init/PreferenceInit.java
src/main/java/hello/roommate/recommendation/controller/RecommendController.java
src/main/java/hello/roommate/recommendation/service/RecommendService.java

- 중복 체크 허용한 항목들 랜덤한 값 여러개 선택 가능하도록 수정

feat: 테스트용 데이터 초기화 함수 수정

---

src/main/java/hello/roommate/init/MemberInit.java
src/main/java/hello/roommate/recommendation/service/RecommendService.java

chore: 테스트용 멤버 수 재설정
